### ISSUE TITLE
Nav Partial is not working in Notifications Controller

### ISSUE THREAD

**Issue by RailsCod3rFuture** [rails-engine/notifications#11]
I'm unable to reach the notifications controller when I click on the link for it. I'm getting `ActionView::Template::Error (undefined local variable or method 'dashboard_index_path' for #<#<Class:0xdccbba0>:0xdcc2e40>): `for some unknown reason. Do I have to define something inside of the notifications_controller.rb?

**Comment by huacnlee** [comment]
try `main_app. dashboard_index_path`

**Comment by RailsCod3rFuture** [comment]
It's working thanks!

**Comment by ecto** [comment]
for anyone who finds this later, you could also add this to your `notifications_controller.rb`:

`helper Rails.application.routes.url_helpers`
